server:
  port: 8081
  error:
    include-stacktrace: always

spring:
  freemarker:
    cache: false

  application:
    name: "burger-finder"

  # i18n
  messages:
    basename: "messages/messages"

  h2:
    console:
      enabled: true
      path: "/h2-console"
